---
  input:
    samples:
      Element_HG002_100x:
        - rg: "@RG\\tID:ElementBio-HG002-1\\tSM:HG002\\tPL:ELEMENT"
          fq:
            - xxx  # Downloaded from https://go.elementbiosciences.com/access-seq-datasets-060622
            - xxx  # Downloaded from https://go.elementbiosciences.com/access-seq-datasets-060622
      Illumina_HG002_HiSeqX_40x:
        - rg: "@RG\\tID:Illumina-HiSeqX-HG002-1\\tSM:HG002\\tPL:ILLUMINA"
          fq:
            - https://s3.amazonaws.com/genomics-benchmark-datasets/google-brain/fastq/hiseqx/wgs_pcr_free/40x/HG002.hiseqx.pcr-free.40x.R1.fastq.gz
            - https://s3.amazonaws.com/genomics-benchmark-datasets/google-brain/fastq/hiseqx/wgs_pcr_free/40x/HG002.hiseqx.pcr-free.40x.R2.fastq.gz
      Illumina_HG002_NovaSeq_40x:
        - rg: "@RG\\tID:Illumina-NovaSeq-HG002-1\\tSM:HG002\\tPL:ILLUMINA"
          fq:
            - https://s3.amazonaws.com/genomics-benchmark-datasets/google-brain/fastq/novaseq/wgs_pcr_free/40x/HG002.novaseq.pcr-free.40x.R1.fastq.gz
            - https://s3.amazonaws.com/genomics-benchmark-datasets/google-brain/fastq/novaseq/wgs_pcr_free/40x/HG002.novaseq.pcr-free.40x.R2.fastq.gz
      PacBio_HG002_HiFi_Chem2:
        - rg: "@RG\\tID:PB-HiFi-Chem2-HG002-1\\tSM:HG002\\tPL:PACBIO"
          fq:
            - "https://s3.amazonaws.com/giab/data/AshkenazimTrio/HG002_NA24385_son/PacBio_CCS_15kb_20kb_chemistry2/reads/m64011_190830_220126.fastq.gz"
        - rg: "@RG\\tID:PB-HiFi-Chem2-HG002-2\\tSM:HG002\\tPL:PACBIO"
          fq:
            - "https://s3.amazonaws.com/giab/data/AshkenazimTrio/HG002_NA24385_son/PacBio_CCS_15kb_20kb_chemistry2/reads/m64011_190901_095311.fastq.gz"
        - rg: "@RG\\tID:PB-HiFi-Chem2-HG002-3\\tSM:HG002\\tPL:PACBIO"
          fq:
            - "https://s3.amazonaws.com/giab/data/AshkenazimTrio/HG002_NA24385_son/PacBio_CCS_15kb_20kb_chemistry2/reads/m64012_190920_173625.fastq.gz"
        - rg: "@RG\\tID:PB-HiFi-Chem2-HG002-4\\tSM:HG002\\tPL:PACBIO"
          fq:
            - "https://s3.amazonaws.com/giab/data/AshkenazimTrio/HG002_NA24385_son/PacBio_CCS_15kb_20kb_chemistry2/reads/m64012_190921_234837.fastq.gz"
        - rg: "@RG\\tID:PB-HiFi-Chem2-HG002-5\\tSM:HG002\\tPL:PACBIO"
          fq:
            - "https://s3.amazonaws.com/giab/data/AshkenazimTrio/HG002_NA24385_son/PacBio_CCS_15kb_20kb_chemistry2/reads/m64015_190920_185703.fastq.gz"
        - rg: "@RG\\tID:PB-HiFi-Chem2-HG002-6\\tSM:HG002\\tPL:PACBIO"
          fq:
            - "https://s3.amazonaws.com/giab/data/AshkenazimTrio/HG002_NA24385_son/PacBio_CCS_15kb_20kb_chemistry2/reads/m64015_190922_010918.fastq.gz"
      ONT_HG002_HPRC:
        - rg: "@RG\\tID:ONT-HPRC-HG002-1\\tSM:HG002\\tPL:ONT"
          fq:
            - "https://human-pangenomics.s3.amazonaws.com/submissions/0CB931D5-AE0C-4187-8BD8-B3A9C9BFDADE--UCSC_HG002_R1041_Duplex_Dorado/Dorado_v0.1.1/stereo_duplex/11_15_22_R1041_Duplex_HG002_1_Dorado_v0.1.1_400bps_sup_stereo_duplex_pass.fastq.gz"
        - rg: "@RG\\tID:ONT-HPRC-HG002-2\\tSM:HG002\\tPL:ONT"
          fq:
            - "https://human-pangenomics.s3.amazonaws.com/submissions/0CB931D5-AE0C-4187-8BD8-B3A9C9BFDADE--UCSC_HG002_R1041_Duplex_Dorado/Dorado_v0.1.1/stereo_duplex/11_15_22_R1041_Duplex_HG002_2_Dorado_v0.1.1_400bps_sup_stereo_duplex_pass.fastq.gz"
        - rg: "@RG\\tID:ONT-HPRC-HG002-3\\tSM:HG002\\tPL:ONT"
          fq:
            - "https://human-pangenomics.s3.amazonaws.com/submissions/0CB931D5-AE0C-4187-8BD8-B3A9C9BFDADE--UCSC_HG002_R1041_Duplex_Dorado/Dorado_v0.1.1/stereo_duplex/11_15_22_R1041_Duplex_HG002_3_Dorado_v0.1.1_400bps_sup_stereo_duplex_pass.fastq.gz"
        - rg: "@RG\\tID:ONT-HPRC-HG002-4\\tSM:HG002\\tPL:ONT"
          fq:
            - "https://human-pangenomics.s3.amazonaws.com/submissions/0CB931D5-AE0C-4187-8BD8-B3A9C9BFDADE--UCSC_HG002_R1041_Duplex_Dorado/Dorado_v0.1.1/stereo_duplex/11_15_22_R1041_Duplex_HG002_4_Dorado_v0.1.1_400bps_sup_stereo_duplex_pass.fastq.gz"
        - rg: "@RG\\tID:ONT-HPRC-HG002-5\\tSM:HG002\\tPL:ONT"
          fq:
            - "https://human-pangenomics.s3.amazonaws.com/submissions/0CB931D5-AE0C-4187-8BD8-B3A9C9BFDADE--UCSC_HG002_R1041_Duplex_Dorado/Dorado_v0.1.1/stereo_duplex/11_15_22_R1041_Duplex_HG002_5_Dorado_v0.1.1_400bps_sup_stereo_duplex_pass.fastq.gz"
        - rg: "@RG\\tID:ONT-HPRC-HG002-6\\tSM:HG002\\tPL:ONT"
          fq:
            - "https://human-pangenomics.s3.amazonaws.com/submissions/0CB931D5-AE0C-4187-8BD8-B3A9C9BFDADE--UCSC_HG002_R1041_Duplex_Dorado/Dorado_v0.1.1/stereo_duplex/11_15_22_R1041_Duplex_HG002_6_Dorado_v0.1.1_400bps_sup_stereo_duplex_pass.fastq.gz"
        - rg: "@RG\\tID:ONT-HPRC-HG002-7\\tSM:HG002\\tPL:ONT"
          fq:
            - "https://human-pangenomics.s3.amazonaws.com/submissions/0CB931D5-AE0C-4187-8BD8-B3A9C9BFDADE--UCSC_HG002_R1041_Duplex_Dorado/Dorado_v0.1.1/stereo_duplex/11_15_22_R1041_Duplex_HG002_7_Dorado_v0.1.1_400bps_sup_stereo_duplex_pass.fastq.gz"
        - rg: "@RG\\tID:ONT-HPRC-HG002-8\\tSM:HG002\\tPL:ONT"
          fq:
            - "https://human-pangenomics.s3.amazonaws.com/submissions/0CB931D5-AE0C-4187-8BD8-B3A9C9BFDADE--UCSC_HG002_R1041_Duplex_Dorado/Dorado_v0.1.1/stereo_duplex/11_15_22_R1041_Duplex_HG002_8_Dorado_v0.1.1_400bps_sup_stereo_duplex_pass.fastq.gz"
        - rg: "@RG\\tID:ONT-HPRC-HG002-9\\tSM:HG002\\tPL:ONT"
          fq:
            - "https://human-pangenomics.s3.amazonaws.com/submissions/0CB931D5-AE0C-4187-8BD8-B3A9C9BFDADE--UCSC_HG002_R1041_Duplex_Dorado/Dorado_v0.1.1/stereo_duplex/11_15_22_R1041_Duplex_HG002_9_Dorado_v0.1.1_400bps_sup_stereo_duplex_pass.fastq.gz"
        - rg: "@RG\\tID:ONT-HPRC-HG002-10\\tSM:HG002\\tPL:ONT"
          fq:
            - "https://human-pangenomics.s3.amazonaws.com/submissions/0CB931D5-AE0C-4187-8BD8-B3A9C9BFDADE--UCSC_HG002_R1041_Duplex_Dorado/Dorado_v0.1.1/stereo_duplex/11_15_22_R1041_Duplex_HG002_10_Dordo_v0.1.1_400bps_sup_stereo_duplex_pass.fastq.gz"
        - rg: "@RG\\tID:ONT-HPRC-HG002-11\\tSM:HG002\\tPL:ONT"
          fq:
            - "https://human-pangenomics.s3.amazonaws.com/submissions/0CB931D5-AE0C-4187-8BD8-B3A9C9BFDADE--UCSC_HG002_R1041_Duplex_Dorado/Dorado_v0.1.1/stereo_duplex/11_15_22_R1041_Duplex_HG002_11_Dorado_v0.1.1_400bps_sup_stereo_duplex_pass.fastq.gz"
      Ultima_HG002_cram:
        url: https://s3.amazonaws.com/ultima-selected-1k-genomes/crams/005401-UGAv3-1-CACATCCTGCATGTGAT.cram
        index: https://s3.amazonaws.com/ultima-selected-1k-genomes/crams/005401-UGAv3-1-CACATCCTGCATGTGAT.cram.crai
    known_sites:
    known_sites:
      dbsnp: https://s3.amazonaws.com/broad-references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf
      mills: https://s3.amazonaws.com/broad-references/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
      known_indels: https://s3.amazonaws.com/broad-references/hg38/v0/Homo_sapiens_assembly38.known_indels.vcf.gz
    dnascope_model:
      Illumina: https://s3.amazonaws.com/sentieon-release/other/DNAscopeIlluminaWGS2.0.bundle
      Illumina_WES: https://s3.amazonaws.com/sentieon-release/other/DNAscopeIlluminaWES2.0.bundle
      Element: https://s3.amazonaws.com/sentieon-release/other/DNAscopeElementBioWGS2.0.bundle
      Ultima: https://s3.amazonaws.com/sentieon-release/other/SentieonUltima1.0.bundle
      PacBio: https://s3.amazonaws.com/sentieon-release/other/DNAscopePacBio2.1.bundle
      ONT: https://s3.amazonaws.com/sentieon-release/other/DNAscopeONT2.1.bundle
  params:
    n_target_bases: 93000000000  # 30x at a 3.1GB genome
  tools:
    sentieon: /home/azureuser/programs/release/arm-sentieon-genomics-202308.01/bin/sentieon
    igzip: /home/azureuser/programs/isa-l/isa-l-2.30.0/programs/igzip
    seqtk: /home/azureuser/programs/seqtk/seqtk/seqtk
    pigz: /home/azureuser/programs/pigz/pigz-2.7/pigz
    bedtools: /home/azureuser/programs/bedtools/2.30.0/bedtools
    samtools: /home/azureuser/programs/samtools/samtools-1.15.1/samtools
    bcftools: /home/azureuser/programs/bcftools/bcftools-1.15.1/bcftools
    rtgtools: /home/azureuser/programs/rtgtools/rtg-tools-3.12.1/rtg
    conda: /home/azureuser/miniconda3/bin/conda
    python2: /home/azureuser/miniconda2/bin/python
    hap.py: /home/azureuser/programs/happy/hap.py-install/bin/hap.py
    sentieon_cli: /home/azureuser/programs/sentieon-cli/.venv/bin/sentieon-cli
